### ISSUE TITLE
Finish up description

### ISSUE THREAD

**Issue by jhollist** [USEPA/cerf_r#1]
Draft of description is started, need to finish and edit.

**Comment by fawda123** [comment]
678c086b310622a9f5b6d44846a7f278f21cc69a What do you think of this?

**Comment by fawda123** [comment]
Alright, here's a draft of the new [description](https://github.com/USEPA/cerf_r/blob/master/description.md) @jhollist

**Comment by jhollist** [comment]
Looks fantastic, @fawda123.  I'd say send it on to Jim.  Will keep this open until we get feedback from him.
